serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
trivy:
  ignoreUnfixed: true
nodeCollector:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
