{{- if not .Values.aws.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traffic.awsSecretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "traffic.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
{{- end }}
